### ISSUE TITLE
加速插件还有的一些问题

### ISSUE THREAD

**Issue by a1134819521** [w4454962/MapHelper#12]
- [x] 1. 当前编辑器打开一张以上地图时。如果两张地图都**存在改动**。退出时选择保存会将编辑器非当前显示的地图保存为当前显示的地图。

- [x]  2. 逆天类型检测在逆天计时器逆天触发器逆天运行触发器中允许重定义一次类型。【看了眼ydwe那边issues好像acb说是没判断属于bug这个不管了】

- [x] 3. 编辑器地形编辑上设置单位，可破坏物掉落物品一堆bug，列如设置随机掉落物品，可破坏物代码中未选中导致未注册事件等。【这个过几天有空修了算了】

**Comment by w4454962** [comment]
啥玩意 修了没
