### ISSUE TITLE
YDWE插件化

### ISSUE THREAD

**Issue by luciouskami** [w4454962/MapHelper#13]
现在MapHelper已经趋于稳定，是时候将其作为YDWE的插件发布了。

**Comment by LazyKnightX** [comment]
它能兼容1.31吗？特指官平的编辑器




---- On Tue, 18 May 2021 20:47:16 +0800 神话 ***@***.***> wrote ----




现在MapHelper已经趋于稳定，是时候将其作为YDWE的插件发布了。

**Comment by w4454962** [comment]
ydwe也已经不更新了 就先这样吧 让用户自己丢到魔兽目录下即可
