### ISSUE TITLE
[BUG] 选取单位组内单位做动作内没有自动插入 local ydl_localvar_step

### ISSUE THREAD

**Issue by LazyKnightX** [w4454962/MapHelper#15]
```
local ydl_localvar_step = LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0x12345678)
```

![image](https://user-images.githubusercontent.com/13707739/119828342-a86b4280-bf2c-11eb-9664-1ceaaf377f16.png)

编译后提示的报错代码如上图，提示缺少 ydl_localvar_step 。
疑似 YDLOCAL_* 插入错误。

演示见压缩包：
[单位组BUG演示.zip](https://github.com/w4454962/MapHelper/files/6571586/BUG.zip)

**Comment by w4454962** [comment]
上传个demo 有人来修的

**Comment by chriscp-cat** [comment]
已经修复过了 但是回退版本了

**Comment by LazyKnightX** [comment]
已上传演示，见主楼附件

**Comment by chriscp-cat** [comment]
921dc04736224144dd68f579d6cd2f7afba5e5b4
查看此次提交 修复了这个bug
